default_language_version:
  python: python3.12
default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]
      - id: check-added-large-files
        stages: [pre-commit]
      - id: check-merge-conflict
        stages: [pre-commit]

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.12
        args: [src/, tests/]

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        language_version: python3.12
        args: [src/, tests/]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: bash -c "python3 -m mypy --python-version=3.12 --ignore-missing-imports --no-strict-optional src/ || true"
        language: system
        types: [python]
        stages: [pre-commit]
        pass_filenames: false
        always_run: true
